name: flida_auth_sdk_android
description: Android implementation of the flida_auth_sdk plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

flutter:
  plugin:
    implements: flida_auth_sdk
    platforms:
      android:
        package: dev.flida.sdk
        pluginClass: FlidaAuthSdkPlugin
        dartPluginClass: FlidaAuthSdkAndroid

dependencies:
  flutter:
    sdk: flutter
  flida_auth_sdk_platform_interface:
    path: ../flida_auth_sdk_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.0.0
